version: '3.9'
services:
    bd-monitoramento:
        image: mysql
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
           MYSQL_DATABASE: rxmonitoramento
           MYSQL_ROOT_USER: root
           MYSQL_ROOT_PASSWORD: root
        networks:
          compose-bridge:
            ipv4_address: 172.20.20.4
        ports:
          - "3306:3306"
        expose: 
          - "3306"

    RxMonitoramento:
        image: grupo5monitoramento/rxmonitoramento:1.0
        container_name: RxMonitoramento
        networks:
          compose-bridge:


networks: 
    compose-bridge: 
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.20.4/16